version: '3'
services:
  computation:
    build: ./computation
    container_name: computation
    ports:
     - "50051:50051"
  api:
    build: ./api
    container_name: api
    ports:
     - "8080:8080"
    depends_on:
      - computation
